import MidiWriter, { Pitch, Duration } from 'midi-writer-js'
import { BassStep } from './StingGenerator'
import { Stage } from '../store/instrumentStore'
import * as Tone from 'tone'
import { GridWalker, SnakePattern } from './GridWalker'

export function exportToMidi(
    bpm: number,
    drums: { kick: number[], snare: number[], hihat: number[], hihatOpen: number[], clap: number[] },
    bassPattern: BassStep[],
    stages: Stage[],
    snakeGrid: { note: number; active: boolean }[] | number[],
    snakePattern: SnakePattern | 'cartesian',
    pads: { notes: string[], active: boolean },
    harmGrid?: { note: number; active: boolean; velocity?: number }[],
    target: 'drums' | 'bass' | 'seq185' | 'snake' | 'pads' | 'harm' | 'turing' = 'drums',
    smartChord?: { enabled: boolean; type: any },
    turingRegister?: number,
    turingBits?: number
): Uint8Array {
    const tracks: MidiWriter.Track[] = []

    // 1. Bass Track
    if (target === 'bass') {
        const track = new MidiWriter.Track()
        track.addTrackName('Acid Bass')
        track.setTempo(bpm, 0)
        for (let bar = 0; bar < 4; bar++) {
            bassPattern.forEach((step) => {
                if (step.active) {
                    track.addEvent(new MidiWriter.NoteEvent({
                        pitch: [step.note] as Pitch[],
                        duration: step.slide ? '8' : '16',
                        velocity: step.accent ? 127 : 90,
                        sequential: true
                    }))
                } else {
                    track.addEvent(new MidiWriter.NoteEvent({ pitch: [], duration: '16', sequential: true }))
                }
            })
        }
        tracks.push(track)
    }

    // 2. Drums Track
    if (target === 'drums') {
        const track = new MidiWriter.Track()
        track.addTrackName('Drums')
        track.setTempo(bpm, 0)
        for (let bar = 0; bar < 4; bar++) {
            for (let step = 0; step < 16; step++) {
                const notes = []
                if (drums.kick[step]) notes.push('C1')
                if (drums.snare[step]) notes.push('D1')
                if (drums.hihat[step]) notes.push('F#1')
                if (drums.hihatOpen[step]) notes.push('A#1')
                if (drums.clap[step]) notes.push('D#1')

                track.addEvent(new MidiWriter.NoteEvent({
                    pitch: notes as Pitch[],
                    duration: '16',
                    sequential: true
                }))
            }
        }
        tracks.push(track)
    }

    // 3. Seq 185 (Rhythm/Gates only or applied to middle C?)
    // User asked for "Seq 185" separate. We'll export the rhythm generated by stages.
    if (target === 'seq185') {
        const track = new MidiWriter.Track()
        track.addTrackName('Seq 185 Rhythm')
        track.setTempo(bpm, 0)

        // We simulate the walker 
        // But strictly speaking ML-185 is just stages. We'll output the stage pitches?
        // In previous design ML-185 didn't have pitch. Now it does (stage.pitch).
        // So we will play stage.pitch with stage timing. 
        // We will IGNORE Snake Grid for this export as it is "Seq 185" specific.
        let pulsesUsed = 0
        const totalPulses = 64
        while (pulsesUsed < totalPulses) {
            for (const stage of stages) {
                if (pulsesUsed >= totalPulses) break
                const stageLengthIn16th = stage.length * stage.pulseCount
                // Use stage pitch
                const noteName = Tone.Frequency(stage.pitch, 'midi').toNote()

                if (stage.gateMode === 0) {
                    track.addEvent(new MidiWriter.NoteEvent({ pitch: [], duration: (stageLengthIn16th).toString() as Duration, sequential: true }))
                } else {
                    // Normalize events for multi/etc (simplified for export)
                    // We'll just put one note for the duration if Single/Hold, multiple if Multi?
                    // Simplified: One note per stage pulse if Multi, else one note.
                    if (stage.gateMode === 2) { // Multi
                        for (let i = 0; i < stageLengthIn16th; i++) {
                            track.addEvent(new MidiWriter.NoteEvent({ pitch: [noteName] as Pitch[], duration: '16', velocity: 100, sequential: true }))
                        }
                    } else {
                        track.addEvent(new MidiWriter.NoteEvent({ pitch: [noteName] as Pitch[], duration: (stageLengthIn16th).toString() as Duration, velocity: 100, sequential: true }))
                    }
                }
                pulsesUsed += stageLengthIn16th
            }
        }
        tracks.push(track)
    }

    // 4. Snake Grid (Just the sequence of notes?)
    // User asked for "MDD Snake" export. Snake is a grid of notes.
    // It depends on the Walker path (Pattern).
    // We will export the sequence of notes generated by the walker traversing the grid 
    // assuming straight 16th notes (since it has no rhythm of its own without 185).
    if (target === 'snake') {
        const track = new MidiWriter.Track()
        track.addTrackName('MDD Snake Sequence')
        track.setTempo(bpm, 0)

        // Simulate walker for 4 bars (64 steps)
        const normalizeGrid = (g: any[]) => g.map(cell => typeof cell === 'number' ? { note: cell, active: true } : cell)
        const grid = normalizeGrid(snakeGrid)

        const path = GridWalker.getPatternPath(snakePattern)
        for (let i = 0; i < 4; i++) { // 4 bars repeated (64 steps total)
            path.forEach(gridIndex => {
                const cell = grid[gridIndex]
                if (cell && cell.active) {
                    const note = Tone.Frequency(cell.note, 'midi').toNote()
                    track.addEvent(new MidiWriter.NoteEvent({ pitch: [note] as Pitch[], duration: '16', velocity: 100, sequential: true }))
                } else {
                    track.addEvent(new MidiWriter.NoteEvent({ pitch: [], duration: '16', sequential: true }))
                }
            })
        }
        tracks.push(track)
    }

    if (target === 'pads') {
        const track = new MidiWriter.Track()
        track.addTrackName('Ambient Pads')
        track.setTempo(bpm, 0)

        if (pads.active) {
            for (let i = 0; i < 4; i++) {
                track.addEvent(new MidiWriter.NoteEvent({
                    pitch: pads.notes as Pitch[],
                    duration: '1',
                    sequential: true,
                    velocity: 50
                }))
            }
        } else {
            track.addEvent(new MidiWriter.NoteEvent({ pitch: [], duration: '4', sequential: true }))
        }
        tracks.push(track)
    }

    if (target === 'harm' && harmGrid) {
        const track = new MidiWriter.Track()
        track.addTrackName('HarmSynth Modular')
        track.setTempo(bpm, 0)

        for (let bar = 0; bar < 4; bar++) {
            harmGrid.forEach(step => {
                if (step.active) {
                    const noteName = Tone.Frequency(step.note, 'midi').toNote()
                    track.addEvent(new MidiWriter.NoteEvent({
                        pitch: [noteName] as Pitch[],
                        duration: '16',
                        velocity: Math.floor((step.velocity || 0.8) * 127),
                        sequential: true
                    }))
                } else {
                    track.addEvent(new MidiWriter.NoteEvent({ pitch: [], duration: '16', sequential: true }))
                }
            })
        }
        tracks.push(track)
    }

    if (target === 'turing' && turingRegister !== undefined) {
        const track = new MidiWriter.Track()
        track.addTrackName('Turing Machine')
        track.setTempo(bpm, 0)

        let reg = turingRegister
        const bits = turingBits || 8
        for (let i = 0; i < 64; i++) {
            // Simple mapping register to scale note (simulated walker logic)
            const noteIndex = reg % 16
            const midiNote = 48 + noteIndex // Simple mapping
            const noteName = Tone.Frequency(midiNote, 'midi').toNote()

            track.addEvent(new MidiWriter.NoteEvent({
                pitch: [noteName] as Pitch[],
                duration: '16',
                velocity: 90,
                sequential: true
            }))

            // Mutate register slightly for variety in export if not locked? 
            // In a real export we'd want the EXACT sequence, but without the full store history
            // we'll just generate based on current register and classic Turing bitwise ops.
            const bit = (reg >> (bits - 1)) & 1
            reg = ((reg << 1) | (Math.random() > 0.5 ? 1 - bit : bit)) & ((1 << bits) - 1)
        }
        tracks.push(track)
    }

    const write = new MidiWriter.Writer(tracks)
    return write.buildFile()
}
